name: build jobs

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code

    - name: dependencies
      run: sudo apt-get install build-essential cmake cppcheck clang-format clang-tidy valgrind

    - name: dependencies
      run: pip install gcovr

    - name: build directory
      run: mkdir build

    - name: CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release   ..
      working-directory: ./build

    - name: build 
      run: cmake --build . -j 
      working-directory: ./build

    - name: tests
      run: ctest --output-junit test_results.xml
      working-directory: ./build

  build_with_warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code

    - name: dependencies
      run: sudo apt-get install build-essential cmake cppcheck clang-format clang-tidy valgrind

    - name: dependencies
      run: pip install gcovr

    - name: build directory
      run: mkdir build

    - name: CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release   ..
      working-directory: ./build

    - name: build 
      run: cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_WARNINGS=ON  ..
      working-directory: ./build
 